<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR4r2in0\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR4r2in0/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerR4r2in0.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerR4r2in0\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerR4r2in0\appProdProjectContainer(array(
    'container.build_hash' => 'R4r2in0',
    'container.build_id' => 'e969ce95',
    'container.build_time' => 1519733318,
));
