<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPklwhay\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPklwhay/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPklwhay.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPklwhay\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerPklwhay\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Pklwhay',
    'container.build_id' => '6cf02206',
    'container.build_time' => 1519780648,
));
