<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRlxfejp\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRlxfejp/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRlxfejp.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRlxfejp\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerRlxfejp\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Rlxfejp',
    'container.build_id' => '1895e8ed',
    'container.build_time' => 1524517806,
));
